/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6JknvR6wR7A
 */


export default function channels() {
  return (
   
<div className="flex h-screen w-full bg-white">
  <div className="flex flex-col w-72 border-r border-gray-200 bg-white dark:bg-gray-900">
    <div className="flex items-center h-16 px-6 border-b border-gray-200 bg-white dark:bg-gray-900">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        className="h-6 w-6 text-gray-500 dark:text-gray-300"
      >
        <path d="M15.5 3H5a2 2 0 0 0-2 2v14c0 1.1.9 2 2 2h14a2 2 0 0 0 2-2V8.5L15.5 3Z"></path>
        <path d="M15 3v6h6"></path>
      </svg>
      <h1 className="ml-2 text-lg font-semibold text-gray-900 dark:text-gray-100">Notes</h1>
    </div>
    <div className="flex-1 overflow-y-auto">
      <div className="py-4 space-y-2">
        <button className="inline-flex items-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2 justify-start text-gray-900 dark:text-gray-100">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            className="h-5 w-5 text-gray-500 dark:text-gray-300"
          >
            <path d="M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.93a2 2 0 0 1-1.66-.9l-.82-1.2A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13c0 1.1.9 2 2 2Z"></path>
          </svg>
          <span className="ml-2">All Notes</span>
        </button>
        <button className="inline-flex items-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2 justify-start text-gray-900 dark:text-gray-100">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            className="h-5 w-5 text-gray-500 dark:text-gray-300"
          >
            <path d="M3 6h18"></path>
            <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"></path>
            <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"></path>
          </svg>
          <span className="ml-2">Trash</span>
        </button>
      </div>
      <div className="border-t border-gray-200 dark:border-gray-800"></div>
      <div className="p-4 space-y-2">
        <div className="flex items-center justify-between px-2 py-1 rounded-lg bg-gray-200 dark:bg-gray-800">
          <span className="text-sm text-gray-900 dark:text-gray-100">Note 1</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            className="h-5 w-5 text-gray-500 dark:text-gray-300"
          >
            <path d="m9 18 6-6-6-6"></path>
          </svg>
        </div>
        <div className="flex items-center justify-between px-2 py-1 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-800">
          <span className="text-sm text-gray-900 dark:text-gray-100">Note 2</span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            className="h-5 w-5 text-gray-500 dark:text-gray-300"
          >
            <path d="m9 18 6-6-6-6"></path>
          </svg>
        </div>
      </div>
    </div>
  </div>
  <div className="flex flex-col flex-1 overflow-hidden">
    <div className="flex items-center h-16 px-6 border-b border-gray-200 bg-white dark:bg-gray-900">
      <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Note 1</h2>
    </div>
    <div className="flex-1 overflow-y-auto p-6 space-y-4">
      <p className="text-sm text-gray-900 dark:text-gray-100">This is a note.</p>
      <p className="text-sm text-gray-900 dark:text-gray-100">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
        dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
        ea commodo consequat.
      </p>
    </div>
  </div>
</div>
  )
}


